settings:
  title: 'Status Page'
  url: 'https://status.watts.one' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: plex-home-watts-one # unique identifier
    name: plex.home.watts.one
    description: 'Plex organizes video, music and photos from personal media libraries and streams them' # default=empty
    url: 'https://plex.home.watts.one/web/index.html' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: glyptodon-home-watts-one
    name: glyptodon.home.watts.one
    description: 'Glyptodon Enterprise is a clientless remote desktop solution powered by Apache Guacamole.'
    url: 'https://glyptodon.home.watts.one/#/'
    method: GET
    expectStatus: 200
